---
title: "scRNA-Seq on WT and Fbw7-deleted U5-NSC"
output: html_notebook
---



```{r}
library(Seurat)
library(SeuratDisk)
library(ggplot2)

setwd("~/count/Fbw7_aggr/outs/raw_feature_bc_matrix/")

```

```{r}
#mtx_obj <- ReadMtx(mtx = "matrix.mtx.gz",
#                   features = "features.tsv.gz",
#                   cells = "barcodes.tsv.gz")
#seurat_mtx <- CreateSeuratObject(counts = mtx_obj, project = "NSC_Fbw7", min.cells = 3, min.features = 200)
#str(seurat_mtx)
```

```{r}
hd5_obj <- Read10X_h5(filename = "../raw_feature_bc_matrix.h5")
str(hd5_obj)
fbw7_obj <- CreateSeuratObject(counts = hd5_obj, project = "NSC_Fbw7", min.cells = 3, min.features = 200)
fbw7_obj #17968 features across 6927 samples

```


```{r}
#QC
View(fbw7_obj@meta.data)
#percent mito genes
fbw7_obj[["percent.mito"]] <- PercentageFeatureSet(fbw7_obj, pattern = "^MT-")
View(fbw7_obj@meta.data)

VlnPlot(fbw7_obj, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"), ncol = 3)


```


```{r}
FeatureScatter(fbw7_obj, feature1 = "nFeature_RNA", "nCount_RNA") +
  geom_smooth(method = "lm")
```

```{r}
#Filtering
fbw7_obj <- subset(fbw7_obj, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mito < 5)
```

```{r}
#Normalization
fbw7_obj <- NormalizeData(fbw7_obj)
str(fbw7_obj)
```

```{r}
# Identify highly variable features
fbw7_obj <- FindVariableFeatures(fbw7_obj, selection.method = "vst", nfeatures = 2000)

top10 <- head(VariableFeaturePlot(fbw7_obj), 10)
top10

Var_plot <- VariableFeaturePlot(fbw7_obj)
Var_plot
Var_plot2 <- LabelPoints(plot = Var_plot, points = rownames(top10), repel = TRUE)
Var_plot2
```

```{r}
#scaling 
#needs to be done dimensional reduction techniques
#mean expression across cells would be 0
#variance across cells would be 1 
#by default only variable features are scaled
#you can specify the features argument to scale additional features
#see SCTransform() for advance options

all.genes <- rownames(fbw7_obj)
fbw7_obj <- ScaleData(fbw7_obj, features = all.genes)


```


```{r}
 fbw7_obj <- RunPCA(fbw7_obj, features = VariableFeatures(object = fbw7_obj))

DimPlot(fbw7_obj, reduction = "pca") + NoLegend()
DimHeatmap(fbw7_obj, dims = 1, cells = 500, balanced = TRUE)
```

```{r}
#detect doublets
remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
library(DoubletFinder)

fbw7_obj <- doubletFinder(fbw7_obj, PCs = 1:10 )
```


```{r}
ElbowPlot(fbw7_pca)
```


```{r}
fbw7_obj <- FindNeighbors(fbw7_obj, dims = 1:10)
fbw7_obj <- FindClusters(fbw7_obj, resolution = 0.5)
head(Idents(fbw7_obj), 5)
```
```{r}
fbw7_obj <- RunUMAP(fbw7_obj, dims = 1:10)
DimPlot(fbw7_obj, reduction = "umap")

saveRDS(fbw7_obj, file = "~/scRNAseq_fbw7.rds")
```

